<?php

use Drupal\emergya_test\Entity\Node\Product;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function emergya_test_entity_bundle_info_alter(&$bundles) {
  if (isset($bundles['node']['product'])) {
    $bundles['node']['product']['class'] = Product::class;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function emergya_test_preprocess_node(&$variables) {

  /** @var \Drupal\node\NodeInterface $node */
  $node = $variables['node'];

  if ('teaser' == $variables['view_mode'] && 'product' == $node->bundle()) {
    if ($node->get('field_protected')->value) {
      $variables['content']['protected'] = ['#markup' => t('This product is protected')];
    }
  }

}
